CREATE DATABASE playdb;

CREATE ROLE learners;

GRANT ALL ON DATABASE playdb TO learners;

CREATE ROLE $AARON_ROLE$ WITH
  IN ROLE learners
  LOGIN PASSWORD '$AARON_PASSWORD$';

CREATE ROLE $DEB_ROLE$ WITH
  IN ROLE learners
  LOGIN PASSWORD '$DEB_PASSWORD$';
