AWSTemplateFormatVersion: 2010-09-09
Description: Create a playground RDS instance

Parameters:
  InstanceName:
    Type: String
    Default: sql-learn-pg
  RootUser:
    Type: String
    NoEcho: True
  RootPassword:
    Type: String
    NoEcho: True
  StackName:
    Type: String
    Default: PlayDb

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Default subnets in default VPC
      DBSubnetGroupName: !Sub "${InstanceName}-sng"
      SubnetIds:
        - subnet-fb74ef8d
        - subnet-d9fb8abd
        - subnet-2a2d9073
      Tags:
        - Key: StackName
          Value: !Ref StackName

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internet access to PlayDB
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
      Tags:
        - Key: StackName
          Value: !Ref StackName

  DbParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for play DB
      Family: postgres14
      Parameters:
        "rds.force_ssl": 1
      Tags:
        - Key: StackName
          Value: !Ref StackName
  
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage : 50
      DBInstanceClass : db.t4g.small
      DBInstanceIdentifier: !Ref InstanceName
      DBParameterGroupName: !Ref DbParameterGroup
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine : postgres
      EngineVersion: 14.2
      MasterUsername : !Ref RootUser
      MasterUserPassword : !Ref RootPassword
      PubliclyAccessible: True
      StorageType: gp2
      VPCSecurityGroups:
        - !GetAtt DbSecurityGroup.GroupId
      Tags:
        - Key: StackName
          Value: !Ref StackName
